version: "3.1"
services:
  user-service:
    container_name: poliChess-user-service
    build:
      dockerfile: Dockerfile
      context: ./user-service
    ports:
      - 3001:3000
    links:
      - mongo

  mongo:
    container_name: poliChess-mongo
    image: mongo
    volumes:
      - ~/data/mongo:/data/db
    command: mongod --quiet --logpath /dev/null 


  matchmaking-service:
    container_name: poliChess-matchmaking-service
    build:
      dockerfile: Dockerfile
      context: ./matchmaking-service
    ports:
      - 3002:3000
    links:
      - postgres

  postgres: 
    container_name: poliChess-postgres
    image: postgres
    volumes:
      - ~/data/postgres:/data/db
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: postgres
  

  game-engine-service:
    container_name: poliChess-game-engine-service
    build:
      dockerfile: Dockerfile
      context: ./game-engine-service
    ports:
      - 3003:3000


  websocket-server:
    container_name: poliChess-websocket-server
    build:
      dockerfile: Dockerfile
      context: ./websocket-server
    ports: 
      - 3004:8080
      - 3005:8080
    links:
      - game-engine-service
      - matchmaking-service


  api-gateway:
    container_name: poliChess-api-gateway
    build:
      dockerfile: Dockerfile
      context: ./api-gateway
    ports: 
      - 3000:3000
    links:
      - user-service
      - matchmaking-service
      - game-engine-service
