version: "3.1"
services:
  user-service:
    container_name: poliChess-user-service
    build:
      dockerfile: Dockerfile
      context: ./user-service
    links:
      - mongo

  mongo:
    container_name: poliChess-mongo
    image: mongo
    volumes:
      - ~/data/mongo:/data/db
    command: mongod --quiet --logpath /dev/null 


  matchmaking-service:
    container_name: poliChess-matchmaking-service
    build:
      dockerfile: Dockerfile
      context: ./matchmaking-service
    links:
      - postgres

  postgres: 
    container_name: poliChess-postgres
    image: postgres
    volumes:
      - ~/data/postgres:/data/db
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: postgres
  

  api-gateway:
    container_name: poliChess-api-gateway
    build:
      dockerfile: Dockerfile
      context: ./api-gateway
    ports: 
      - 3000:3000
    links:
      - user-service
      - matchmaking-service
